source-file ~/.config/tmux/tmux.reset.conf
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# Prefix settings
unbind C-b
set -g prefix C-b
bind C-b send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### TRANSPARENT STATUS BAR #####
set -g status-style bg=default
set -g status-left-length 60
set -g status-right-length 120
set -g window-status-separator ""

##### LEFT PILL (session + host) - BLUE #####
# fg=blue for the start curve
# bg=blue, fg=black for the text content
# fg=blue, bg=default for the end curve
set -g status-left "#[fg=blue]#[fg=black,bg=blue]#S #[fg=blue,bg=default] "

##### WINDOW PILLS #####
# Focused window - RED
set -g window-status-current-format "#[fg=red]#[fg=black,bg=red]#I 󱎂 #W#[fg=red,bg=default] "

# Unfocused window - WHITE (Standard terminal white/gray)
# Using white here so it doesn't clash with the Red/Blue/Yellow highlights
set -g window-status-format "#[fg=white]#[fg=black,bg=white]#I 󱎂 #W#[fg=white,bg=default] "

##### RIGHT PILL (time) - YELLOW #####
set -g status-right "#[fg=yellow]#[fg=black,bg=yellow]󰃰 %Y-%m-%d %H:%M#[fg=yellow,bg=default] "
